language: python
python:
    - "3.5"
    - "3.4"
sudo: required
before_script:
    - psql -c "create database sdx;" -U postgres
    - psql -c "create user sdx with password 'sdx';" -U postgres
    - psql -c "grant all privileges on database sdx to sdx;" -U postgres
    - psql -d sdx -a -f setup/schema.sql -U sdx
before_install:
    - git clone https://github.com/ONSdigital/sdx-common.git
    - pip3 install ./sdx-common
install:
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt
    - pip install codecov
script:
    - make test
    - coverage run tests/test*.py
dist: trusty
after_success:
    - codecov
services:
    - postgresql
addons:
   postgresql: "9.6"
