language: python
dist: xenial
python:
    - "3.7"
    - "3.6"
sudo: required
before_install:
    - pip install --upgrade pip
install:
    - make build
    - pip install codecov
    - pip install -r test_requirements.txt
script:
    - make test
    - pytest -v tests/ --cov=server --cov-report html
dist: trusty
after_success:
    - codecov
services:
    - postgresql
